### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [PaulBatchelor/Soundpipe#1]
I would like to point out that an identifier like "[`__SOUNDPIPE_H__`](https://github.com/PaulBatchelor/Soundpipe/blob/2c4d149dc5503d28989372a27ae9a267ba3f3361/h/base.h#L9)" [does not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by PaulBatchelor** [comment]
Thank you for pointing that out! I fixed it.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/PaulBatchelor/Soundpipe/commit/6c9e5ad9e071ae764e5df8c83954ad46832d457e#diff-1eac0dfdc68143b6a9d3ba2fdd761d9aL9 "Deletion of a few underscores").
Are there any more update candidates to consider?
