### ISSUE TITLE
Connecting soundpipe modules together

### ISSUE THREAD

**Issue by emurray2** [PaulBatchelor/Soundpipe#1]
I just learned how to create an Audio Unit with Soundpipe and AudioKit, and I tried out the sp_saturator which works great! Then, I wanted to see if it is possible to connect two Soundpipe modules together. For example, would it work to initialize all the modules I want connected in order and then call `sp_saturator_compute()` and `sp_delay_compute()` after eachother? I'm still a beginner at C++, so I'm not sure how to manage concurrency. However, I read somewhere that Soundpipe wraps each module inside Patchwerk, so I was wondering if this behavior of patching modules is setup by default.

This is what my DSP Process method looks like:

```
 void process(AUAudioFrameCount frameCount, AUAudioFrameCount bufferOffset) override {
        for (int frameIndex = 0; frameIndex < frameCount; ++frameIndex) {
            int frameOffset = int(frameIndex + bufferOffset);
            // get ramped drive value
            float drive = driveRamp.getAndStep();
            // set drive parameter in soundpipe saturators
            saturator0->drive = drive;
            saturator1->drive = drive;
            // get ramped dc offset value
            float dcOffset = dcOffsetRamp.getAndStep();
            // set dc offset parameter in soundpipe saturators
            saturator0->dcoffset = dcOffset;
            saturator1->dcoffset = dcOffset;
            // get ramped delay time value
            float delayTime = delayTimeRamp.getAndStep();
            // set delay time parameter in soundpipe delays
            delay0->time = delayTime;
            delay1->time = delayTime;
            // create stereo input and output channels
            float *tmpin[2];
            float *tmpout[2];
            // channelCount - from "DSPBase.h"
            for (int channel = 0; channel < channelCount; ++channel) {
                // distributed objects - pointing to the input and output data rendered
                float *in = (float *)inputBufferLists[0]->mBuffers[channel].mData + frameOffset;
                float *out = (float *)outputBufferList->mBuffers[channel].mData + frameOffset;
                // conditional - limits the in and out channels to 2
                if (channel < 2) {
                    // connect the input channel to the input port of the processor
                    tmpin[channel] = in;
                    // connect the output channel to the output port of the processor
                    tmpout[channel] = out;
                }
                // if the DSPBase is not started, do this:
                if (!isStarted) {
                    // bypass the processing - just connect the plugin input to plugin output
                    *out = *in;
                    // move onto the next loop cycle
                    continue;
                }
                // assign left channel to saturator 1 and right channel to saturator 2
                // assign left channel to delay 1 and right channel to delay 2
                if (channel == 0) {
                    sp_saturator_compute(sp, saturator0, in, out);
                    sp_delay_compute(sp, delay0, in, out);
                } else {
                    sp_saturator_compute(sp, saturator1, in, out);
                    sp_delay_compute(sp, delay1, in, out);
                }
            }
        }
    }
```

It's exactly how AudioKit wraps Soundpipe modules in a Node. I've just never seen one Node contain multiple Soundpipe modules yet.

Also, this is more of a question than an issue. Please let me know if there is a better place to leave questions in the future. Thank you!

--Evan

**Comment by PaulBatchelor** [comment]
Route the output from the saturator too the delay line, you'd need to use some temporary variable to hold the output of the saturator, which then gets fed into the input of the delay line:

```
SPFLT tmp;
sp_saturator_compute(sp, saturator0, in, &tmp);
sp_delay_compute(sp, delay0, &tmp, out);
```

Soundpipe actually doesn't do any kind of automated patch/graph management. It just does numerical computation. The way I'm using pointers here makes this less obvious, but what I'm doing above is equivalent to the following pseudocode:

```
tmp = saturator(in)
out = delay(tmp)
```

I use pointers instead of this return-style syntax because it's a way to get multiple return values from a function. A "patch", as far as Soundpipe is concerned, is just a bunch of operations being called in the right order, with outputs of each operation being saved and stored somewhere long enough so that they can be processed by some future operation expecting it as input.

Hope that helps.

-P

**Comment by emurray2** [comment]
@PaulBatchelor That's exactly the info I needed! Thank you so much for your help and quick response! I can't wait to explore this library some more.
