### ISSUE TITLE
ADSR durations in seconds

### ISSUE THREAD

**Issue by intonarumori** [PaulBatchelor/Soundpipe#106]
I've been running the [example code for the ADSR](https://github.com/PaulBatchelor/Soundpipe/blob/master/examples/ex_adsr.c) functions with the following parameters:
```
    ud.adsr->atk = 0;
    ud.adsr->dec = 0.5;
    ud.adsr->sus = 0;
    ud.adsr->rel = 0;
```
After looking at the generated output file (`test.wav`) the sound length matches the 5 seconds documented in the readme but the overall decay duration seems to be around 2-2.5 seconds.

The [online documentation](http://paulbatchelor.github.io/res/soundpipe/docs/adsr.html) says: `dec: Decay time (in seconds)`

Is this the expected behaviour and the documentation is a little bit off or am I setting it up wrong?

Many thanks.

**Comment by intonarumori** [comment]
@PaulBatchelor Thanks Paul.
I'm definitely fine with the implementation itself, I was thinking about the UI for my envelopes and what units I could display for my sliders. I might just measure the duration for the maximum value I provide and that's good enough.

I'm actually working with AudioKit where the Soundpipe ADSR is used but couldn't get them working properly. Before creating an issue there I decided to build an AudioKit node from the ground up without ramping to understand the problem better.

Thanks for the clear and detailed response.

**Comment by PaulBatchelor** [comment]
> I might just measure the duration for the maximum value I provide and that's good enough.

Great. Since nobody seems to be too terribly bothered by this quirk, I've decided to leave things alone for now. It probably will be best to update the docs at some point. Once I've done that, I'll close this issue.

**Comment by PaulBatchelor** [comment]
Documentation has been updated in 35d856fcf8a. Closing this issue now.
