### ISSUE TITLE
Specifying orders for butterworth filters

### ISSUE THREAD

**Issue by imilas** [PaulBatchelor/Soundpipe#113]
Hello and thanks for this great library. 

I was wondering if there's a way to specify the order when creating butterworth filters, similar to what's possible in [scipy's implementation](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.signal.butter.html). 
Looking at the docs it seems like that's not implemented, but I'm not very familiar with C (I'm using this library through [pippi](https://github.com/luvsound/pippi)) so maybe I missed something.

**Comment by PaulBatchelor** [comment]
Thank you for the kind words!

Unfortunately, the short answer is no, there is no way to specify order with any of the butterworth filter implementations. Sorry about that. These filters are directly ported from the Csound opcode, which are also hard-coded as 2nd order filters. In an effort to preserve backwards compatibility, I'd rather leave these modules alone. I mean this in the nicest possible way. Maybe someday there will be new butterworth filters that allow the user to specify order?

If you need a steeper order filter, you can always work two of these in series. Two of them in series is the equivalent of a 4th order filter, for instance.

If makes sense to you at some point, I highly highly recommend checking out some of the [standard library FAUST filters](https://faust.grame.fr/doc/libraries/index.html#butterworth-lowpasshighpass-filters). They have butterworth implementations that let you specify order at compile-time, which then get transpiled down to optimized C++ code (amongst other backends).

**Comment by imilas** [comment]
That's a shame, but I understand your reasoning. The series idea is a good alternative though, thank you.
