### ISSUE TITLE
Build fails when make invocation overrides CFLAGS

### ISSUE THREAD

**Issue by xelxebar** [PaulBatchelor/Soundpipe#115]
## Overview

Starting from a vanilla 1.7.0 source tree, I am attempting to package soundpipe for Void Linux[2]. However, the build fails with the following error:

    ...
    cc -Wall -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -pipe    -c -static modules/base.c -o modules/base.o
    modules/base.c:8:10: fatal error: soundpipe.h: No such file or directory
        8 | #include "soundpipe.h"
          |          ^~~~~~~~~~~~~
    ...

Looking at the above `cc` invocation, it is clear that the appropriate `CFLAGS` are not getting picked up. This is happening because Void's package builds provide a `CFLAGS` [variable override][0] to their `make` invocations.

## Proposed Fix

Currently, I am working around the problem by patching [override directives][1] to all the `CFLAGS` variable assignments:

    $ find -regex '.*Makefile\|.*config.def.mk' -exec sed -i 's/^\(\s*\)CFLAGS/\1override CFLAGS/' '{}' \+

Since it looks like the makefiles are already using GNU extensions, perhaps it would be reasonable to also upstream the above? 

[0]:https://www.gnu.org/software/make/manual/html_node/Overriding.html#Overriding
[1]:https://www.gnu.org/software/make/manual/html_node/Override-Directive.html#Override-Directive
[2]:https://voidlinux.org/

**Comment by PaulBatchelor** [comment]
This looks like a brute force solution to a very specific problem. I would recommend using a custom `config.mk` instead.

**Comment by xelxebar** [comment]
Agreed. This shouldn't be fixed on the soundpipe end. Thanks for taking a look.
