### ISSUE TITLE
Is `out` in `SPFLOAT *out;` meant to be used as a keyword?

### ISSUE THREAD

**Issue by emurray2** [PaulBatchelor/Soundpipe#116]
Hi Paul,

I'm a music tech student at Georgia Tech, and I am really inspired by the work you do with Soundpipe and AudioKit!

I just have a quick question (rather than an issue). I am poking around in some of the Soundpipe header files to better understand them, and I came across something which caught my attention.

In soundpipe.h I was looking at the `sp_data` struct and noticed there is a pointer `SPFLOAT *out;`. In Xcode, `out` shows up as a keyword, and I was just wondering if it was meant to be used as a keyword in this case. I know C++ does not have a keyword called `out`, but I read somewhere that Objective-C does, so that makes sense why Xcode would read it as that.

<img width="241" alt="Screen Shot 2020-03-10 at 2 53 15 PM" src="https://user-images.githubusercontent.com/15041342/76355236-4a801a00-62ea-11ea-9245-f9fca6198f34.png">

I'm assuming it's just meant to be used as a regular pointer rather than a keyword, but I just wanted to make sure I'm not missing something. 

--Evan

**Comment by PaulBatchelor** [comment]
The short unhelpful answer to that is: no, it is not a keyword.

You are correct in your assumption:`out` is a floating point array that gets allocated at run time. It gets used by `sp_out` or set directly. This value is then used inside of the `sp_process` function to generate wav files via libsndfile. The reason why it is an array is to support multichannel (multi-mono) output.

It's interesting that Xcode isn't able to properly figure that out. `SPFLOAT` is just a C macro, that can be set to be `float` or `double` at compile time. By default, floating point precision is used. This concept originated from the Csound codebase, and I decided to keep it in.

Hope that helps. Enjoy your time at Georgia Tech. It's a great program.

**Comment by emurray2** [comment]
@PaulBatchelor Sounds good! That is very helpful, and now I understand better.

Thank you so much for the help!
