### ISSUE TITLE
Linking libsndfile on Mac OS Catalina

### ISSUE THREAD

**Issue by emurray2** [PaulBatchelor/Soundpipe#117]
Hi again!

I've been working on coding my own module for a program called VCV Rack. I want to try and use Soundpipe as a library in my plugin. I am able to get the source code to compile successfully. However, it seems like VCV Rack is having issues accessing libsndfile at runtime, and my plugin won't load. Here is the output I get in the log:

`[3.991 warn src/plugin.cpp:158] Could not load plugin /Users/evanmurray/Documents/Rack/plugins/EVMusic: Failed to load library /Users/evanmurray/Documents/Rack/plugins/EVMusic/plugin.dylib: dlopen(/Users/evanmurray/Documents/Rack/plugins/EVMusic/plugin.dylib, 6): Symbol not found: _sf_close
  Referenced from: /Users/evanmurray/Documents/Rack/plugins/EVMusic/plugin.dylib
  Expected in: flat namespace
 in /Users/evanmurray/Documents/Rack/plugins/EVMusic/plugin.dylib`

Any advice on fixing this helps! You can find all of the source code [here](https://github.com/emurray2/EVMusic-Rack/blob/master/EVMusic/src/ModularForecast.cpp).

I've noticed that the plugin fails I try to initiate Soundpipe in ModularForecast.cpp on line 282.

Thank you!

--Evan

**Comment by PaulBatchelor** [comment]
long story short, you need to link libsndfile.

Try adding `-lsndfile` to LDFLAGS in your [Makefile](https://github.com/emurray2/EVMusic-Rack/blob/master/EVMusic/Makefile#L11) and see what happens.

**Comment by emurray2** [comment]
@PaulBatchelor Sweet! It worked! It wasn't working at first until I ran `make clean` in terminal, and then I did `make` after I updated the makefile, and everything is running smoothly now. Thank you so much!
