### ISSUE TITLE
Soundpipe in VisualStudio C++ (problem to run)

### ISSUE THREAD

**Issue by DigitalPilgrim** [PaulBatchelor/Soundpipe#118]
Hello

I downloaded this library and compile it with msys2. It was done without any problem, problem is, how to use this library in C++ project in VisualStudio? I have VS 2017 CE and 2019 CE,

When I look at what was msys2 produce there are lot of *.o file. They are not usable for VisualStudio.
Then I add all *.c files in to c++ project, but after some code correction and Preprocessor definitions I end up with this errors:
for example soundpipe-c\lib\openlpc\ftol.h(10): error C2065: 'fistp': undeclared identifier in Soundpipe-c\lib\openlpc\openlpc.c
or
openlpc.c(221): error C2065: 'd': undeclared identifier

If I something "repair" new errors arise. I am not C programer, and have no much experience with msys2, but it looks like, msys2 not produce "windows output". If I am right, how to compile or install Soundpipe in windows correctly?

**Comment by PaulBatchelor** [comment]
It looks like a problem with the openlpc library included in Soundpipe. Specifically, the windows version of the local ftol function seems to be broken:

https://github.com/PaulBatchelor/Soundpipe/blob/master/lib/openlpc/ftol.h#L10

If you're not planning using the LPC module, you can disable openlpc and the lpc module by opting out of compiling lib/openlpc/openlpc.c and modules/lpc.c. That should fix this this problem.

I'd be also curious about seeing what happens when you don't use the `ifdef _MSC_VER` macro in lib/openlpc/ftol.h, by making the header look something like this:

```c
#ifdef __GNUC__
/* must define _GNU_SOURCE here or in the makefile */
#include <math.h>
#else

#define FP_BITS(fp) (*(int *)&(fp))
#define FIST_FLOAT_MAGIC_S (float)(7.0f * 2097152.0f)

static int lrintf(float inval)
{
    float tmp = FIST_FLOAT_MAGIC_S + inval;
    int res = ((FP_BITS(tmp)<<10)-0x80000000);
    return res>>10;
}
#endif
```

**Comment by PaulBatchelor** [comment]
@DigitalPilgrim any updates?

**Comment by DigitalPilgrim** [comment]
Hello, I am sorry but I didn't test it yet. I apologize for long wait, I forgot about it. As soon as I test it I come back and give a response.

**Comment by PaulBatchelor** [comment]
@DigitalPilgrim progress on this issue?

**Comment by DigitalPilgrim** [comment]
Hello
I change header file as you describe in post, but I got error for sp_fft.c file, there was no `#include` therefore I add this one
`#include <sp_base.h>`.
Another problem is, with libsnd. I don't know how to not include it into project I just change make file into this

```
ifndef NO_LIBSNDFILE
	CFLAGS += -DNO_LIBSNDFILE
else
	CFLAGS += -DNO_LIBSNDFILE
endif
```

and compilation throw this:
`fatal error C1083: Cannot open include file: 'sndfile.h': No such file or directory`

**Comment by PaulBatchelor** [comment]
It doesn't seem like the `NO_LIBSNDFILE` is sticking. If you're using this inside a VisualStudio project, you'll probably need to set CFLAGS from the project settings, not the Makefile.

**Comment by DigitalPilgrim** [comment]
This compilation error is with this `NO_LIBSNDFILE` CFLAG set in VisualStudio project.

**Comment by PaulBatchelor** [comment]
Which file exactly is complaining about the the sndfile.h issue? If `NO_LIBSNDFILE` is enabled, the macro should prevent the include from happening. Did you do a full clean before attempting to recompile?

**Comment by DigitalPilgrim** [comment]
After clean I get this errors:

```
Error	C2036	'void *': unknown size	soundpipe1plug	d:\programi\development\audio\soundpipe\soundpipe-c\modules\revsc.c	75	
Error	C2491	'lrintf': definition of dllimport function not allowed (compiling source file ..\..\..\..\..\..\..\Programi\Development\Audio\Soundpipe\Soundpipe-c\lib\openlpc\openlpc.c)	soundpipe1plug	d:\programi\development\audio\soundpipe\soundpipe-c\lib\openlpc\ftol.h	11	
Error	C2057	expected constant expression	soundpipe1plug	d:\programi\development\audio\soundpipe\soundpipe-c\lib\openlpc\openlpc.c	214	
Error	C2466	cannot allocate an array of constant size 0	soundpipe1plug	d:\programi\development\audio\soundpipe\soundpipe-c\lib\openlpc\openlpc.c	214	
Error	C2133	'r': unknown size	soundpipe1plug	d:\programi\development\audio\soundpipe\soundpipe-c\lib\openlpc\openlpc.c	214	
Error	C1083	Cannot open include file: 'sndfile.h': No such file or directory	soundpipe1plug	d:\programi\development\audio\soundpipe\soundpipe-c\modules\diskin.c	4	

```

Now I discovered that I had source files in project (openlpc.c and diskin.c). After exlude those files from project, errors are dissapeared except this one:
```
Error	C2036	'void *': unknown size	soundpipe1plug	d:\programi\development\audio\soundpipe\soundpipe-c\modules\revsc.c	75	
Error (active)	E0852	expression must be a pointer to a complete object type	soundpipe1plug	D:\Programi\Development\Audio\Soundpipe\Soundpipe-c\modules\revsc.c	75	
```

**Comment by PaulBatchelor** [comment]
I remember running into this exact issue on Windows a few years ago. If memory serves me correctly, the compiler used doesn't like it when you manipulate void pointers directly. The solution is to cast it to a `char *`.

The offending line (line 75 of revsc on master of writing):

```
p->delayLines[i].buf = (p->aux.ptr) + nBytes;
```

Change that to:

```
p->delayLines[i].buf = ((char *) p->aux.ptr) + nBytes;
```
In the [LMMS port of revsc](https://github.com/LMMS/lmms/commit/d4f4500359f078c99f325551724514207f425c29#diff-9c257c3f0afe218f75e2e3fb92f68a7a), I guess they also needed to cast it to `SPFLOAT` to avoid compiler warnings. You may also need to do this:

```
p->delayLines[i].buf = (SPFLOAT*) (((char*) p->aux.ptr) + nBytes);
```

(I know... it's not pretty, but that's because this operation is doing an unsafe C thing that C++ generally squawks about (they may be using a C++ compiler on the above code).)

Let me know if that helps...

**Comment by DigitalPilgrim** [comment]
It looks like it is fixed, I used this code
`p->delayLines[i].buf = (SPFLOAT*) (((char*) p->aux.ptr) + nBytes);`

but new errors arise

```
1>sp_fft.obj : error LNK2001: unresolved external symbol POW2
1>sp_fft.obj : error LNK2001: unresolved external symbol fftCosInit
1>sp_fft.obj : error LNK2001: unresolved external symbol rffts1
1>sp_fft.obj : error LNK2001: unresolved external symbol ffts1
1>sp_fft.obj : error LNK2001: unresolved external symbol riffts1
1>lpc.obj : error LNK2001: unresolved external symbol init_openlpc_encoder_state
1>lpc.obj : error LNK2001: unresolved external symbol openlpc_encode
1>lpc.obj : error LNK2001: unresolved external symbol init_openlpc_decoder_state
1>lpc.obj : error LNK2001: unresolved external symbol openlpc_decode
1>lpc.obj : error LNK2001: unresolved external symbol openlpc_sr
1>lpc.obj : error LNK2001: unresolved external symbol openlpc_get_encoder_state_size
1>lpc.obj : error LNK2001: unresolved external symbol openlpc_get_decoder_state_size
1>plugprocessor.obj : error LNK2001: unresolved external symbol "int __cdecl sp_create(struct sp_data * *)" (?sp_create@@YAHPEAPEAUsp_data@@@Z)
1>plugprocessor.obj : error LNK2001: unresolved external symbol "int __cdecl sp_destroy(struct sp_data * *)" (?sp_destroy@@YAHPEAPEAUsp_data@@@Z)
1>plugprocessor.obj : error LNK2001: unresolved external symbol "int __cdecl sp_delay_create(struct sp_delay * *)" (?sp_delay_create@@YAHPEAPEAUsp_delay@@@Z)
1>plugprocessor.obj : error LNK2001: unresolved external symbol "int __cdecl sp_delay_destroy(struct sp_delay * *)" (?sp_delay_destroy@@YAHPEAPEAUsp_delay@@@Z)
1>plugprocessor.obj : error LNK2001: unresolved external symbol "int __cdecl sp_delay_init(struct sp_data *,struct sp_delay *,float)" (?sp_delay_init@@YAHPEAUsp_data@@PEAUsp_delay@@M@Z)
1>plugprocessor.obj : error LNK2001: unresolved external symbol "int __cdecl sp_delay_compute(struct sp_data *,struct sp_delay *,float *,float *)" (?sp_delay_compute@@YAHPEAUsp_data@@PEAUsp_delay@@PEAM2@Z)
```

**Comment by PaulBatchelor** [comment]
Ah. Missing symbols. I think I know why most of them are happening.

Things like `POW2` and `fftCosInit` are found in fftlib.c, which are not exported. You need to combine `fftlib.c` and `sp_fft.c` into a generated file called `fft.c`.

This is Makefile rule used:

```
$(LIBDIR)/fft/fft.c: lib/fft/fftlib.c lib/fft/sp_fft.c | $(LIBDIR)/fft
	echo "/* THIS IS A GENERATED FILE. DO NOT EDIT BY HAND */" > $@
	cat $^ >> $@
```

It can be as simple as copy-pasting `fftlib.c` and `sp_fft.c` into one file in that order.

The openlc functions are related to the openlpc library that you were having trouble compiling earlier. Did you end up including it? If not, you'll need to remove the lpc modules found in `modules/lpc.c`.

`sp_create` and `sp_destroy` are functions found in `modules/base.c`. Are you compiling + linking this file?

the `sp_delay_` prefixed functions are found in `modules/delay.c`. Are you compiling + linking this file?

**Comment by DigitalPilgrim** [comment]
> Things like POW2 and fftCosInit are found in fftlib.c, which are not exported. You need to combine fftlib.c and sp_fft.c into a generated file called fft.c.
> t can be as simple as copy-pasting fftlib.c and sp_fft.c into one file in that order.

Fortunately `fft.c is` ok. I had included `fftlib.c` and `sp_fft.c ` in project what create those errors. After exclude it from project, thoser errors gone:
```
1>sp_fft.obj : error LNK2001: unresolved external symbol POW2
1>sp_fft.obj : error LNK2001: unresolved external symbol fftCosInit
1>sp_fft.obj : error LNK2001: unresolved external symbol rffts1
1>sp_fft.obj : error LNK2001: unresolved external symbol ffts1
1>sp_fft.obj : error LNK2001: unresolved external symbol riffts1
1>lpc.obj : error LNK2001: unresolved external symbol init_openlpc_encoder_state
1>lpc.obj : error LNK2001: unresolved external symbol openlpc_encode
1>lpc.obj : error LNK2001: unresolved external symbol init_openlpc_decoder_state
1>lpc.obj : error LNK2001: unresolved external symbol openlpc_decode
1>lpc.obj : error LNK2001: unresolved external symbol openlpc_sr
1>lpc.obj : error LNK2001: unresolved external symbol openlpc_get_encoder_state_size
1>lpc.obj : error LNK2001: unresolved external symbol openlpc_get_decoder_state_size
```

> sp_create and sp_destroy are functions found in modules/base.c. Are you compiling + linking this file?
the sp_delay_ prefixed functions are found in modules/delay.c. Are you compiling + linking this file?

For both questions: Yes.

Btw. I forgot mentio problem with spa.c

```
warning MSB8027: Two or more files with the name of spa.c will produce outputs to the same location. This can lead to an incorrect build result.  The files involved are ..\..\..\..\..\..\..\Programi\Development\Audio\Soundpipe\Soundpipe-c\lib\spa\spa.c, ..\..\..\..\..\..\..\Programi\Development\Audio\Soundpipe\Soundpipe-c\modules\spa.c.
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol spa_write_buf	soundpipe1plug	D:\Moje Dokumenty\Programovanie\Moje Programi\Visual Studio 2017\Audio\vst_soundpipe\soundpipe1plug\sparec.obj	1	
Error	LNK2001	unresolved external symbol spa_open	soundpipe1plug	D:\Moje Dokumenty\Programovanie\Moje Programi\Visual Studio 2017\Audio\vst_soundpipe\soundpipe1plug\spa.obj	1	
Error	LNK2001	unresolved external symbol spa_open	soundpipe1plug	D:\Moje Dokumenty\Programovanie\Moje Programi\Visual Studio 2017\Audio\vst_soundpipe\soundpipe1plug\sparec.obj	1	
Error	LNK2001	unresolved external symbol spa_read_buf	soundpipe1plug	D:\Moje Dokumenty\Programovanie\Moje Programi\Visual Studio 2017\Audio\vst_soundpipe\soundpipe1plug\spa.obj	1	
Error	LNK2001	unresolved external symbol spa_close	soundpipe1plug	D:\Moje Dokumenty\Programovanie\Moje Programi\Visual Studio 2017\Audio\vst_soundpipe\soundpipe1plug\spa.obj	1	
Error	LNK2001	unresolved external symbol spa_close	soundpipe1plug	D:\Moje Dokumenty\Programovanie\Moje Programi\Visual Studio 2017\Audio\vst_soundpipe\soundpipe1plug\sparec.obj	1	
```

if I exclude `spa.c` from project (included from `Soundpipe-c\modules\spa.c` this problem gone, but I am not sure if it is ok, to not include `spa.c` from `modules` folder.

**Comment by PaulBatchelor** [comment]
> if I exclude spa.c from project (included from Soundpipe-c\modules\spa.c this problem gone, but I am not sure if it is ok, to not include spa.c from modules folder.

no one needs spa. I promise you you will never use spa. if it is giving you pain, go on right ahead and remove it.

so, what problems are left now?

**Comment by DigitalPilgrim** [comment]
This:

```
Error	LNK2001	unresolved external symbol "int __cdecl sp_delay_compute(struct sp_data *,struct sp_delay *,float *,float *)" (?sp_delay_compute@@YAHPEAUsp_data@@PEAUsp_delay@@PEAM2@Z)	soundpipe1plug	D:\Moje Dokumenty\Programovanie\Moje Programi\Visual Studio 2017\Audio\vst_soundpipe\soundpipe1plug\plugprocessor.obj	1	
Error	LNK2001	unresolved external symbol "int __cdecl sp_destroy(struct sp_data * *)" (?sp_destroy@@YAHPEAPEAUsp_data@@@Z)	soundpipe1plug	D:\Moje Dokumenty\Programovanie\Moje Programi\Visual Studio 2017\Audio\vst_soundpipe\soundpipe1plug\plugprocessor.obj	1	
Error	LNK2001	unresolved external symbol "int __cdecl sp_delay_create(struct sp_delay * *)" (?sp_delay_create@@YAHPEAPEAUsp_delay@@@Z)	soundpipe1plug	D:\Moje Dokumenty\Programovanie\Moje Programi\Visual Studio 2017\Audio\vst_soundpipe\soundpipe1plug\plugprocessor.obj	1	
Error	LNK2001	unresolved external symbol "int __cdecl sp_delay_destroy(struct sp_delay * *)" (?sp_delay_destroy@@YAHPEAPEAUsp_delay@@@Z)	soundpipe1plug	D:\Moje Dokumenty\Programovanie\Moje Programi\Visual Studio 2017\Audio\vst_soundpipe\soundpipe1plug\plugprocessor.obj	1	
Error	LNK2001	unresolved external symbol "int __cdecl sp_delay_init(struct sp_data *,struct sp_delay *,float)" (?sp_delay_init@@YAHPEAUsp_data@@PEAUsp_delay@@M@Z)	soundpipe1plug	D:\Moje Dokumenty\Programovanie\Moje Programi\Visual Studio 2017\Audio\vst_soundpipe\soundpipe1plug\plugprocessor.obj	1	
Error	LNK2001	unresolved external symbol "int __cdecl sp_create(struct sp_data * *)" (?sp_create@@YAHPEAPEAUsp_data@@@Z)	soundpipe1plug	D:\Moje Dokumenty\Programovanie\Moje Programi\Visual Studio 2017\Audio\vst_soundpipe\soundpipe1plug\plugprocessor.obj	1	

```

**Comment by PaulBatchelor** [comment]
It looks to me like you are using the `sp_delay` module in some C++ code somewhere. If so, are you using `extern "C"` when including the soundpipe header? Otherwise, the C++ compiler will not be able to "see" the C symbols.

Something like:

```
extern "C" {
#include "soundpipe.h"
}
```

**Comment by PaulBatchelor** [comment]
FYI, it looks like you are trying to build a vst plugin. `sp_delay` is a static delay whose delay time cannot be parametrically adjusted. It probably wouldn't be all useful for a plugin. I'd recommend either [vdelay](https://paulbatchelor.github.io/res/soundpipe/docs/vdelay.html) or [smoothdelay](https://paulbatchelor.github.io/res/soundpipe/docs/smoothdelay.html).

**Comment by DigitalPilgrim** [comment]
Thanks, after this update code was finnaly compiled without problem.

**Comment by DigitalPilgrim** [comment]
> FYI, it looks like you are trying to build a vst plugin. sp_delay is a static delay whose delay time cannot be parametrically adjusted. It probably wouldn't be all useful for a plugin. I'd recommend either vdelay or smoothdelay.

 Yes I am working on vst plugin. Thank you for warning.

**Comment by PaulBatchelor** [comment]
Great! It seems like the initial issue has been solved, so I am closing this out now. Good luck.
