### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [PaulBatchelor/Soundpipe#2]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/PaulBatchelor/Soundpipe/blob/4e54a57ba0d71f72b0eabd5ea4ac7dba1ee27a87/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](http://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by flyondrag** [comment]
Well, I'm highly reccomend pick the CMake instead of Autotools, otherwise one of the modern build system like https://waf.io/.

**Comment by PaulBatchelor** [comment]
What current problems will a build system solve? At the moment, this isn't a kind of automation I plan on introducing. If I were to do that, it would more than double the dependencies needed for this project, as well add significant amounts of code to this project. This doesn't make sense with the size or scope of the project.

**Comment by elfring** [comment]
* How do you think about to [improve the software portability with configuration checks](http://www.gnu.org/software/automake/manual/html_node/Generalities.html "General ideas")?
* Would you like to [support parallel build trees](http://cmake.org/Wiki/CMake_FAQ#What_is_an_.22out-of-source.22_build.3F "Out-of-source build trees")?

**Comment by PaulBatchelor** [comment]
I think that a c99 c compiler, the standard C library, and make are portable enough. I really like the fact that I can compile SP on very small embedded linux distributions like Alpine Linux. 

I don't see why I would want parallel build trees...? 

Thank you for your suggestions, but these aren't solving problems, they are adding features that I don't think I need.

**Comment by elfring** [comment]
* Does [a tool like "autoscan"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
* How do you think about to support more development environments by [the reuse of build system generators](http://www.cmake.org/cmake/help/v3.2/manual/cmake-generators.7.html#cmake-generators "Selection for build tool generators")?
