### ISSUE TITLE
Live input - ALSA

### ISSUE THREAD

**Issue by DavidVentura** [PaulBatchelor/Soundpipe#6]
Hi
I'd like to pipe mic input (live) from ALSA to a lowpass+highpass filter (4k, 100hz) to avoid having to do this in postproduction (or if I can't, pipe the prod audio to avoid doing it manually on audacity)

Can I do this? How?

**Comment by PaulBatchelor** [comment]
You could use the butterworth lowpass and highpass filters. They are "butlp" and "buthp", one pair per channel of input.

I'd like a little bit more info about your needs. What are you capturing with the microphone? What are you using for a computer? Is this an embedded system, a Pi, or a desktop computer? 

I really have no idea how I'd do it using ALSA. That API is very frustrating to use. If using JACK is a possibility, you could pretty easily build such a static filter using the jack API and route the signal that way. 

If you can't use JACK, I'd probably recommend going the offline route and write a program that processes soundfiles using libsndfile. The libsndfile examples folder has a pretty good example of such a program here: https://github.com/erikd/libsndfile/blob/master/examples/sfprocess.c

**Comment by DavidVentura** [comment]
I'm using a raspberry pi (ATM the B, but will swap to 2 soon), I'm
currently using it for live streaming (skin-care courses) with the
camera+microphone. The mic picks up some background noise during the
stream, afterwards I process it with the filters.

I'll try and set up jack (I have some audio quality issues on alsa anyway)

On 7 July 2015 at 16:30, Paul Batchelor <notifications@github.com> wrote:

> You could use the butterworth lowpass and highpass filters. They are
> "butlp" and "buthp", one pair per channel of input.
>
> I'd like a little bit more info about your needs. What are you capturing
> with the microphone? What are you using for a computer? Is this an embedded
> system, a Pi, or a desktop computer?
>
> I really have no idea how I'd do it using ALSA. That API is very
> frustrating to use. If using JACK is a possibility, you could pretty easily
> build such a static filter using the jack API and route the signal that
> way.
>
> If you can't use JACK, I'd probably recommend going the offline route and
> write a program that processes soundfiles using libsndfile. The libsndfile
> examples folder has a pretty good example of such a program here:
> https://github.com/erikd/libsndfile/blob/master/examples/sfprocess.c
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PaulBatchelor/Soundpipe/issues/6#issuecomment-119310565>
> .
>



-- 
*Stack* is the new term for "I have no idea what I'm actually using".

**Comment by PaulBatchelor** [comment]
Can you describe how you are doing the streaming? 

Unrelated, but if you are just trying to filter out ambient room sound, the noise reduction filter works pretty well (it may also sound better than using the filters).

**Comment by DavidVentura** [comment]
raspivid [....] | ffmpeg -f [] -i - -f alsa -i hw:0 [....] -f flv
rtmp://[..]

On 7 July 2015 at 16:42, Paul Batchelor <notifications@github.com> wrote:

> Can you describe how you are doing the streaming?
>
> Unrelated, but if you are just trying to filter out ambient room sound,
> the noise reduction filter works pretty well (it may also sound better than
> using the filters).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PaulBatchelor/Soundpipe/issues/6#issuecomment-119314650>
> .
>



-- 
*Stack* is the new term for "I have no idea what I'm actually using".

**Comment by PaulBatchelor** [comment]
Have you tried using the -af flag in ffmpeg?

http://superuser.com/questions/733061/reduce-background-noise-and-optimize-the-speech-from-an-audio-clip-using-ffmpeg
