### ISSUE TITLE
CUI.h from faust

### ISSUE THREAD

**Issue by frink** [PaulBatchelor/Soundpipe#64]
Doesn't the inclusion of this file force the entire library to become GPL 3?

I'm looking at the possibility of using this in an upcoming project, but this inclusion concerns me.

**Comment by PaulBatchelor** [comment]
Good catch. The FAUST branch is indeed GPLv2.

I'll talk to the Faust devs about having a dual license for this, or I'll find a way to do away with this file altogether.

Only the modules made in FAUST use this, so you can opt not to build those modules and you'll  be fine.

**Comment by PaulBatchelor** [comment]
I have rewritten CUI.h so it doesn't directly use the FAUST code. This has been fixed now.
