### ISSUE TITLE
Ability to build and install in separate directories

### ISSUE THREAD

**Issue by dennisvennink** [PaulBatchelor/Soundpipe#70]
I'm currently looking into libraries for a synthesizer I'm working on. Since it targets multiple architectures I need the ability to build and install the library into separate directories.

I understand from #2 that you're not interested in adding a build system generator. I completely understand this; I prefer to write my Makefiles by hand as well and don't appreciate the extra overhead. 

So what I propose is the addition of two variables `INTERMEDIATE_DIR` and `PRODUCT_DIR` in the Makefile that enable you to set both directories at compile time:

``` sh
make INTERMEDIATE_DIR="..."
make install INTERMEDIATE_DIR="..." PRODUCT_DIR="..."
```

Let me know if you're interested so I can implement it and send you a pull request. :thumbsup:

**Comment by PaulBatchelor** [comment]
I like the idea, as long as these variables are set by default so that
things work the same. Preferably should be set in config.mk.

Would INTERMEDIATE_DIR be where all the .o files go and PRODUCT_DIR be
where the library installs to (should be called PREFIX set to /usr/local by
default)?

-P

**Comment by dennisvennink** [comment]
> I like the idea, as long as these variables are set by default so that
things work the same.

Yes. make has a conditional variable assignment operator, `?=`, that does exactly that.

> Would INTERMEDIATE_DIR be where all the .o files go and PRODUCT_DIR be
where the library installs to (should be called PREFIX set to /usr/local by
default)?

The intermediates directory would default to `.` and would include everything that gets built or generated: the static library, the object files, the header, the docs, etc. The product or installation directory would default to `/usr/local` and copies the archive and the header file over from the intermediates directory. I was also thinking that the HTML docs could be installed into `/usr/local/share/doc`.

Since you like the idea let's discuss what to call these variables. `prefix` or `PREFIX` might indeed be better for the installation directory since that's pretty much the standard naming convention. For the intermediates I'd suggest something like `intermediates_prefix` or `INTERMEDIATES_PREFIX` then, keeping it in line with the other variable.

**Comment by PaulBatchelor** [comment]
I prefer using all caps for makefile variables. PREFIX and
INTERMEDIATES_PREFIX.

HTML docs should go in /usr/local/share/doc.

This all sounds good. When you have finished this, make a PR on dev.

Thanks!

-P

**Comment by PaulBatchelor** [comment]
Thank you for your changes! I have merged your changes, and did some fixes of my own. Can you make sure I didn't break anything for your needs?

I did mostly cosmetic stuff to abide by the 80 column real. I decided against installing documentation for now because creating the documentation requires lua, which to me is an optional dependency.

**Comment by dennisvennink** [comment]
Looks good. 👍
