### ISSUE TITLE
Instructions/examples for realtime sound generation

### ISSUE THREAD

**Issue by xavriley** [PaulBatchelor/Soundpipe#76]
Apologies in advance if I've missed something, but I was hoping to embed Soundpipe in a simple live coding language. I don't have a lot of experience with low-level audio (I'm coming from a SuperCollider background) but would it be possible to write the audio directly to `/dev/audio` instead of generating a wav file?

Any tips on how to approach this would be much appreciated. Thanks for your time.

**Comment by PaulBatchelor** [comment]
It's very possible to do realtime audio with Soundpipe. I've done this myself with [Sporth](http://www.pbat.ch/proj/sporth.html), which is a language that supports live coding.

The easiest way to get audio coming out of your speakers would be to use soundpipe with an audio library like portaudio, rtaudio, or libsoundio. I do not have any good examples of this, but these audio libraries often have good starter code; it wouldn't be too difficult of a stretch to inject Soundpipe calls in the right places.

**Comment by xavriley** [comment]
Cool thanks for the pointers - I'm checking out rtAudio and I'll report back if I get a working example setup.

If you have any examples of livecoding with Sporth I'd be interested to check that out too! From the docs I could only see wav file generation but again, I may be missing something.

**Comment by PaulBatchelor** [comment]
If you are on Linux, you can mimic my Sporth live coding setup. I use JACK and Vim. I have written a blog post about it [here](http://pbat.ch/blog/posts/2016-08-01-sporth_live_coding.html).

**Comment by PaulBatchelor** [comment]
@xavriley I hope you don't mind, but I am closing this issue. I personally don't like lingering github issues to pile up, and this isn't the sort of issue isn't actionable enough. Please see the post I above about live coding with Sporth, and feel free to reach out whenever!

For future Soundpipers, I will leave a few tidbuts:

1. Soundpipe doesn't directly support platform specific hardware for realtime. It only has the DSP algorithms. There is no plan for Soundpipe to do this. (A graphics parallel to this would be OpenGL, where you need a platform specific library for windowing to work with GL)

2. Soundpipe performs quite well in realtime. Projects like AudioKit and Sporth use Soundpipe under the hood. 

3. Any of the major cross platform audio libraries should be able to handle Soundpipe. All you'd need to do is place your sp_compute functions inside their supplied callback loop for audio. I've tested this with RtAudio and PortAudio for sure.

4. For Linux users, there are some deprecated optional modules in soundpipe called sp_jack and sp_rpi (for the raspberry pi). I have not tested these for quite some time, so they are probably broken.
