### ISSUE TITLE
data folder probably needs update.

### ISSUE THREAD

**Issue by fennecdjay** [PaulBatchelor/Soundpipe#77]
While I was working on a lua script to generate code to import soundpipe in [Gwion](https://github.com/fennecdjay/Gwion), I noticed a few things that migth be errors.

  *  *progress* and *tblrec* declared with no out
  * incorrect mandatory params for *nsmp* and *gen_scrambler*
  * *gen_scrambler* could document **&sp_ftbl*** for *dest* param, as it takes **&dest** as argument.
  * *padsynth* name not beginning by **gen_**
  * a few module (e.g; compressor) use **SPFLOAT*** whereas documented as **SPFLOAT**
        this could be fixed with a simple sed script:   
```
 sed -i s/SPFLOAT/SPFLOAT\*/  <file>  
```
this [gist](https://gist.github.com/fennecdjay/bceb8afa5591454949421ef7ead7e3ca) contains a *diff* file that fixes this all. simply do
```
patch -p1 < data_update.diff
```
in soundpipe's root directory.  
At least this fixes things for me.

P.S. I would really enjoy to know whether you managed to build Gwion or not.  
thanks for this library.

**Comment by PaulBatchelor** [comment]
Thank you for the pull request! Will have to look at this closer before I
merge it.

Was unable to compile Gwion on my Slackware system, but it looks very
promising. I told Ge about it and he was very interested.

**Comment by PaulBatchelor** [comment]
Oh this is a patch not a PR (on my phone). Happy to apply it, but why not
make a pull request on the dev branch?

**Comment by PaulBatchelor** [comment]
This is now a pull request: see #78
