### ISSUE TITLE
Is there a tutorial to convert C Sound to Soundpipe? 

### ISSUE THREAD

**Issue by danicejewishboy** [PaulBatchelor/Soundpipe#85]
I really respect all the work you have done with audiokit and soundpipe. I want to create more audiokit modules based on Csound. Where could I find documentation to convert Csound to SoundPipe?

**Comment by PaulBatchelor** [comment]
Thank you for using Soundpipe! I'm glad it has been useful for you so far.

I have some drafts of a tutorial for converting Csound opcodes to Soundpipe modules. If you email me at thisispaulbatchelor at gmail dot com, I can send that to you.

I can also recommend the chapter on Csound opcodes in the Audio Programming Book, which is where I started out with Soundpipe.

Are there specific opcodes you have in mind? Before you start anything, please be sure to make a github issue with the opcode you want to port.

**Comment by PaulBatchelor** [comment]
Closing this for the following reasons:

1. I have answered the main question. (There are no official tutorials online for writing Soundpipe modules from Csound). 

2. You have emailed me personally about specific opcodes. I have replied to these.
