### ISSUE TITLE
Adding Red/Brownian Noise

### ISSUE THREAD

**Issue by russellbstephens** [PaulBatchelor/Soundpipe#86]
Would it be possible to add a red/brownian noise component?

**Comment by PaulBatchelor** [comment]
Probably. I'll look into it.

**Comment by PaulBatchelor** [comment]
A quick google lead me to this C++ class: http://vellocet.com/dsp/noise/VRand.h

I can probably extract the algorithm for brown noise and turn it into a soundpipe module.

**Comment by PaulBatchelor** [comment]
Done! "sp_brown" has been added in the dev branch.

**Comment by russellbstephens** [comment]
Nice!

**Comment by russellbstephens** [comment]
Would it be easy for you to add this to AudioKit?

**Comment by PaulBatchelor** [comment]
I wouldn't be able to do this, but others know how. I'd ask about it on
Google groups. Link the GitHub issue here.

**Comment by aure** [comment]
@russellbstephens I'll add it tonight.

**Comment by aure** [comment]
@russellbstephens https://github.com/audiokit/AudioKit/commit/4e3c236460fc063b3bd276c57a406628309e1e93

**Comment by russellbstephens** [comment]
wow! thanks
