### ISSUE TITLE
gen_sine lacks documentation file.

### ISSUE THREAD

**Issue by fennecdjay** [PaulBatchelor/Soundpipe#88]
Almost everything in the title.
I can make a PR if you like, but I choosed to file an issue first, as I'm unsure what doc string you prefer.

**Comment by PaulBatchelor** [comment]
Thank you for making an issue first before doing a PR!

Use this for reference:

https://github.com/PaulBatchelor/Soundpipe/blob/master/modules/data/gen_line.lua
 
You can just remove the params field altogether.

**Comment by fennecdjay** [comment]
see #89.
