### ISSUE TITLE
runtime control of sp_process?

### ISSUE THREAD

**Issue by belm0** [PaulBatchelor/Soundpipe#95]
I'm wondering if you've considered having a sp_process() shim which can branch to an implementation (generate WAV, JACK, plot) based on environment variable.

I think it would be immediately useful, at least for the examples.

**Comment by PaulBatchelor** [comment]
This would actually break my Sporth project, which currently can select the various backends using a command line flag. Plus, I don't expect all platforms to support environment variables. 

Thanks for the suggestion though!
