### ISSUE TITLE
JACK example has hard-coded sample rate

### ISSUE THREAD

**Issue by belm0** [PaulBatchelor/Soundpipe#99]
i.e. it's not using the sample rate appropriate for the JACK port, so playback will be at wrong frequency

Pull request #98 tries to workaround this in the client code, but this exposes a Soundpipe API issue.   ```sp_jack_process()``` should accept a JACK client object so that programs can open a single JACK client to ascertain the port sample rate as well as customize any JACK parameters before handing it to Soundpipe.

**Comment by PaulBatchelor** [comment]
Thank you for bringing this to my attention. 

sp_jack is very old and deprecated part of Soundpipe. It was initially created to easily test out realtime capabilities for Soundpipe on Linux. These days, I simply use Soundpipe with [RtAudio](https://github.com/thestk/rtaudio) for cross platform audio support.

**Comment by PaulBatchelor** [comment]
An update to my previous comment:

After much consideration, I have decided to remove both the Raspberry Pi (ALSA) and Jack Soundpipe modules from the source code distribution. These modules are out of the design scope for this project. Soundpipe is built to be as platform neutral as possible: it focuses on *just* the signal processing. It is up to the Soundpipe user to implement the audio backend for their specific platform. This decision is what keeps Soundpipe highly portable and easy to maintain.

Using Soundpipe in a realtime audio setting is typically a pretty straightforward process: just don't use the sp_process function and call the sp_compute functions directly in your audio render callback.
